[DO_SO]
scope.complete.codebase = {context = true, review = true, integration = true } # SETS THE SCOPE TO COMPLETE FRONT TO BACK REPOSITORY REVIEW
src.identify = { placeholders = true, incomplete_code = true, dead_code = true, missing_entirely = true } # IDENTIFY AND CORRECT ALL NOTED CATEGORIES
src.module = { improvements = true, completions = true, error_corrections = true, code_quality_improvements = true, optimizations = true } # CURRENT REQUIREMENTS FOR MODULES
src.code_quality.improvements = { working_file = true, always_review = true } # ALWAYS IMPROVE THE CODE QUALITY OF THE CURRENT WORKING FILE WHERE APPLICABLE
src.code_QOL.features = true # ALWAYS IMPROVE USER EXPERIENCE WHERE POSSIBLE
optimizations.module.implementations = true # OPTIMIZE FOR SPEED, MEMORY, AND RESOURCE USAGE


[DO_NOT]
ask.permission = false # PERMISSION IS IMPLIED BY THIS NOTE
remove.unused_variables = false # ONLY PERMITTED FOR DUPLICATIONS, OR DEPRECIATED CODE
correction.format.allow_delete = { duplication = true, deprecation = true, else = false } # SETS PERMISSIONS FOR DELETING CODE, ELSE PERMISSION IS FALSE BY DEFAULT
